### ISSUE TITLE
v0 tracking issue

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/mizu#34]
- [x] Compatibility and examples
  - [x] deno
  - [x] browsers 
  - [x] others (node, bun)
- [x] Logo  
- [x] Website
  - [x] Main page 
  - [x] Playground
  - [x] Coverage
- [x] Documentation
  - [x] Features 
  - [x] Demo 
  - [x] FAQ 
  - [x] Usage 
  - [x] Concepts
  - [x] Rendering schema 
  - [x] Directives
  - [x] API 
    - [x] User 
      - [x] Client
      - [x] Server
    - [x] Developer
      - [x] Directives
      - [x] Internal  
  - [x] TBD
- [x] Publishing
  - [x] jsr.io
- [x] Directives
  - [x] #18 
  - [x] #14 
  - [x] #23
  - [x] #9 
  - [x] #13 
  - [x] #24 
  - [x] #8 
  - [x] #10 
  - [x] #4 
  - [x] #25 
  - [x] #5 
  - [x] #7 
  - [x] #15 
  - [x] #1 
  - [x] #19 
  - [x] #32
  - [x] #6 
  - [x] #16 
  - [x] #21 
  - [x] #17 
  - [x] #11 
  - [x] #12 
  - [x] #2 
  - [x] #3 
  - [x] #22  
- [x] Repository
  - [x] Workflows
  - [x] Licenses
  - [x] Issue templates
  - [x] Pull request templates
- [x] Contribution
  - [x] Contributing guide
  - [x] Contributor License Agreement
