### ISSUE TITLE
Upstream issues tracking

### ISSUE THREAD

**Issue by lowlighter** [lowlighter/mizu#48]
> [!WARNING]
> This is an umbrella issue that covers bug encountered during development but are due to upstream bugs.
> Usually a workaround is found in the meantime (if possible) so this is more for maintainers' reference

### Scope

repo

### Deno

- [ ] `npx tsx` cannot be run through `deno task`
  - https://github.com/denoland/deno/issues/27166
  - https://github.com/denoland/docs/issues/1270
  - [x] *workaround: use `npm test` instead* 
- [ ] `deno.jsonc` cannot use `workspaces: [ "@mizu/*" ]` because it breaks bundling resolution
  - https://github.com/lucacasonato/esbuild_deno_loader/issues/156
  - [x] *workaround: manually list workspace members*
- [ ] `deno.jsonc` have some `sleep 0` tasks as placeholder (empty command not supported)
  - https://github.com/denoland/deno/issues/27165  
  - [x] *workaround: keep `sleep 0` as placeholder*
- [ ] `denoland/deployctl` github action does not behaves the same as the cli version
  - https://github.com/denoland/deployctl/issues/350
  - [x] *workaround: parse flags and pass them back as step outputs* 
  - https://github.com/lowlighter/mizu/blob/7a03e8f9ac8bae70cc937b6505fdc9fa74d5bab7/.github/workflows/ci.yml#L61-L63
  - https://github.com/lowlighter/mizu/blob/7a03e8f9ac8bae70cc937b6505fdc9fa74d5bab7/.github/tools/github_actions_deno_deploy.ts#L16-L25
- [ ] `deployctl` conflicts with dependencies installed by npm jsr (e.g. `Error: The deployment failed: npm package '@jsr/dprint__formatter' does not exist.`)
  - https://github.com/denoland/deno/issues/27380 
  - https://github.com/denoland/deployctl/pull/351
  - [x] *workaround: remove lock files and package.json to "reset" the lock file*
  - https://github.com/lowlighter/mizu/blob/7a03e8f9ac8bae70cc937b6505fdc9fa74d5bab7/.github/workflows/ci.yml#L64
  - https://github.com/lowlighter/mizu/blob/7a03e8f9ac8bae70cc937b6505fdc9fa74d5bab7/.github/tools/github_actions_deno_deploy.ts#L10-L14
- [ ] Bad fmt in `mod.html` files
  - https://github.com/denoland/deno/issues/27374
  - [ ] **No fixes, but not breaking** 
- [ ] Support `cleanUrls` natively for easy HTTP serving
  - https://github.com/denoland/std/issues/6232
  - [x] *Workaround: use forked version https://jsr.io/@lowlighter/std-http* 

### Deno doc
- [ ] The new version of `@deno/doc@^0.162.1` is not able to generate documentation for local modules
  - https://github.com/denoland/deno_doc/issues/680
  - [x] *Workaround: downgrade to version `0.161`* 
```
Error: relative URL without a base
    at __wbg_new_28c511d9baebfa89 (https://jsr.io/@deno/doc/0.162.1/deno_doc_wasm.generated.js:651:19)
    at <anonymous> (wasm://wasm/011a3ff2:1:136374)
    at <anonymous> (wasm://wasm/011a3ff2:1:3139281)
    at <anonymous> (wasm://wasm/011a3ff2:1:3723228)
    at __wbg_adapter_51 (https://jsr.io/@deno/doc/0.162.1/deno_doc_wasm.generated.js:290:6)
    at real (https://jsr.io/@deno/doc/0.162.1/deno_doc_wasm.generated.js:274:14)
    at ext:core/01_core.js:291:9
    at eventLoopTick (ext:core/01_core.js:175:7)
``` 

### Node

- [x] `npx tsx --test` does not find tests on the github runner (but works as expected locally) 
  - *fixed: was using an outdated version of node*

### Bun

- [ ] `bun test` currently ignores all tests wrapped by the `mod_test.html` test runner
  - https://github.com/oven-sh/bun/issues/11660
  - [ ] **NO FIXES, BUN COMPATIBILITY CANNOT BE GUARANTEED ATM**
- [ ] Cannot pin `oven-sh/setup-bun` to `1.x`
  - https://github.com/oven-sh/setup-bun/issues/37
  - [x] *Workaround: use `latest` instead*
- [ ] JSDOM doesn't work with bun/windows 
  - Possibly related to https://github.com/oven-sh/bun/issues/5835 ?
  - See *Ref [1]*
  - [ ] **NO FIXES, BUN COMPATIBILITY WITH WINDOWS CANNOT BE GUARANTEED ATM**

*Ref [1]:*
```
# Unhandled error between tests
  -------------------------------
  
  Error: 
        at 2:1
  1 | (function (entry, fetcher)
      ^
  SyntaxError: Export named 'JSDOM' not found in module 'D:\a\mizu\mizu\node_modules\jsdom'.
  -------------------------------
```
